project:
  type: book
  output-dir: docs

book:
  title: "MA{VR}X Lab Manual"
  author: "Ryan Straight"
  date: last-modified
  description: "This is the lab manual for the Mixed Augmented ViRtual eXtended Reality Lab in the College of Applied Science and Technology at the University of Arizona."
  favicon: images/square-solid.jpg
  twitter-card: true
  page-footer:
    left: |
      <a href="https://mavrxlab.org/">MA{VR}X Lab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://mavrxlab.github.io/manual/
  repo-url: https://github.com/mavrxlab/manual
  repo-actions: [edit,issue]
  downloads: [pdf, epub]


  chapters:
    - index.qmd
    - about.qmd
    - roles.qmd
    - onboarding.qmd
    - spaces.qmd
    - comms.qmd
    - meetings.qmd
    - practice-protocols.qmd
    - dissemination.qmd
    - summary.qmd
    - references.qmd
  appendices: 
    - project-step-by-step.qmd
    - faq.qmd

bibliography: references.bib

#margin-header: |
#  ![Logo image](images/square-solid.jpg)

editor_options:
  markdown:
    wrap: 72
    canonical: true
    
execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  html:
    theme: zephyr
    number-depth: 0
  epub: default
  pdf:
    documentclass: scrreprt
    cap-location: margin
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex