gantt
  dateFormat  YYYY-MM
  section Administrative
    Semester start                      :adm1, 2023-01-11, 1d
  	Lab onboarding                      :onboarding, after adm1, 4d
    Meet with lab director              :labdir, after onboarding, 1d
  	Initial reading                     :reading, after labdir, 6d
    Complete IRB                        :irb, after reading, 10d
    Create OSF project, pre-register    :osf, after irb, 4d
  section Data
    Data collection                     :data1, after osf, 2w
    Lab internal brownbag               :brownbag, after data1 , 2d
  section Writing
    Introduction and methods            :methods, after data1, 2w
    Full rough draft                    :fullrough, after methods, 2w
    Practice talk                       :ptalk, after fullrough, 1d
  	Final written draft                 :finaldraft, after ptalk, 2w
  	Presentation                        :presentation, after finaldraft, 2d