gantt
  dateFormat  YYYY-MM-DD
  section Administrative
  Semester start                      :adm1, 2023-01-11, 1d
	Lab onboarding                      :onboarding, after adm1, 1d
  Meet with lab director              :labdir, after onboarding, 1d
	Initial reading                     :reading, after labdir, 3d
  Complete IRB                        :irb, after reading, 5d
  Create OSF project, pre-register    :osf, after irb, 2d
  section Data
  Data collection                     :data1, after osf, 1w
  Lab internal brownbag               :brownbag, after data1 , 1d
  section Writing/Production
  Introduction and methods            :methods, after data1, 5d
  Full rough draft                    :fullrough, after methods, 7d
  Practice talk                       :ptalk, after fullrough, 1d
	Final written draft                 :finaldraft, after ptalk, 7d
	Presentation                        :after finaldraft, 1d
